#!/bin/python
# coding: utf-8

import subprocess as sp
import sys

def get_staged_files():
  p = sp.Popen(['git', 'status', '--porcelain'],
      stdin=sp.PIPE, stdout=sp.PIPE, stderr=sp.STDOUT,
      close_fds=True)

  files = []
  while True:
    line = p.stdout.readline()
    if not line:
      break
    status, filepath = line[:2], line[3:].rstrip('\n')
    if status[:1] == 'A' or status[:1] == 'M':
      files.append(filepath)
  return files

def check_changelog():
  p = sp.Popen(['git', 'diff', 'ChangeLog'],
      stdin=sp.PIPE, stdout=sp.PIPE, stderr=sp.STDOUT,
      close_fds=True)
  while True:
    line = p.stdout.readline()
    if not line:
      break
    # ChangeLog の中身確認


if __name__ == '__main__':
  result = 1

  for f in get_staged_files():
    if f == "ChangeLog":
      result = 0

  print result
  sys.exit(result)

